# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    app.admin_email: 'mmelustondo@gmail.com'
    app.admin_linked_en: 'https://www.linkedin.com/in/mercedes-elustondo-27609b84/?locale=en_US'
    app.admin_linked_fr: 'https://www.linkedin.com/in/mercedes-elustondo-27609b84/?locale=fr_FR'
    app.admin_linked_es: 'https://www.linkedin.com/in/mercedes-elustondo-27609b84/'
    app.owner.name: ELUSTONDO Maria de las Mercedes EI
    app.owner.address: Montpellier
    app.owner.siret: 915 708 851 00014
    app.owner.tva_immatriculation: 
    app.host_information: Hostinger International Ltd - 61 Lordou Vironos str., 6023 Larnaca, Cyprus - compliance@hostinger.com

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
    
    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
    App\Service\MailerService:
        arguments:
            $admin_email: '%app.admin_email%'
    App\EventSubscriber\LocaleSubscriber:
        arguments: ['%kernel.default_locale%']
    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
